spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - dev
  sql:
    init:
      platform: postgresql
      mode: never
  jwt:
    secretKey: "c2lsdmVybmluZS1"
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        show_sql: true
        #        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    context-path: /union
    session:
      timeout: 7200
